package service;

import model.Contact;
import model.MBTI;

import java.io.*;
import java.nio.charset.StandardCharsets;
import java.time.LocalDateTime;
import java.util.*;

public class ContactManager {
    private static final String CONTACTS_FILE = "data/contacts.txt";
    private Map<String, Contact> contacts;
    
    public ContactManager() {
        this.contacts = new HashMap<>();
        loadContacts();
        System.out.println("📇 연락처 매니저 초기화 완료 (연락처 " + contacts.size() + "개)");
    }
    
    public void saveContact(Contact contact) {
        if (contact == null || contact.getName() == null || contact.getName().trim().isEmpty()) {
            return;
        }
        
        contacts.put(contact.getName(), contact);
        saveToFile();
        System.out.println("💾 연락처 저장: " + contact.getDisplayInfo());
    }
    
    public Contact getContact(String name) {
        return contacts.get(name);
    }
    
    public boolean hasContact(String name) {
        return contacts.containsKey(name);
    }
    
    public List<Contact> getAllContacts() {
        List<Contact> list = new ArrayList<>(contacts.values());
        list.sort(Comparator.comparing(Contact::getName));
        return list;
    }
    
    public Set<String> getAllContactNames() {
        return new TreeSet<>(contacts.keySet());
    }
    
    public void setMbti(String name, MBTI mbti) {
        Contact contact = contacts.get(name);
        if (contact != null) {
            contact.setMbti(mbti);
            saveToFile();
            System.out.println("✅ MBTI 설정: " + name + " → " + mbti.getCode());
        }
    }
    
    public void setNotes(String name, String notes) {
        Contact contact = contacts.get(name);
        if (contact != null) {
            contact.setNotes(notes);
            saveToFile();
        }
    }
    
    public void setAutoGeneratedProfile(String name, String profile) {
        Contact contact = contacts.get(name);
        if (contact != null) {
            contact.setAutoGeneratedProfile(profile);
            saveToFile();
            System.out.println("✅ 자동 프로필 저장: " + name);
        }
    }

    public void deleteContact(String name) {
        if (contacts.remove(name) != null) {
            saveToFile();
            System.out.println("🗑️ 연락처 삭제: " + name);
        }
    }
    
    public void clearAll() {
        contacts.clear();
        saveToFile();
        System.out.println("🗑️ 모든 연락처 삭제");
    }
    
    private void saveToFile() {
        try {
            File dataDir = new File("data");
            if (!dataDir.exists()) {
                dataDir.mkdirs();
            }
            
            try (PrintWriter writer = new PrintWriter(
                new OutputStreamWriter(new FileOutputStream(CONTACTS_FILE), StandardCharsets.UTF_8))) {
                
                for (Contact contact : contacts.values()) {
                    writer.println(contactToString(contact));
                }
            }
        } catch (IOException e) {
            System.err.println("❌ 연락처 저장 실패: " + e.getMessage());
            e.printStackTrace();
        }
    }
    
    private void loadContacts() {
        File file = new File(CONTACTS_FILE);
        if (!file.exists()) {
            System.out.println("📄 연락처 파일이 없습니다. 새로 시작합니다.");
            return;
        }
        
        try (BufferedReader reader = new BufferedReader(
            new InputStreamReader(new FileInputStream(file), StandardCharsets.UTF_8))) {
            
            String line;
            int loadCount = 0;
            
            while ((line = reader.readLine()) != null) {
                Contact contact = stringToContact(line);
                if (contact != null) {
                    contacts.put(contact.getName(), contact);
                    loadCount++;
                }
            }
            
            System.out.println("✅ " + loadCount + "개의 연락처를 불러왔습니다.");
            
        } catch (IOException e) {
            System.err.println("❌ 연락처 로드 실패: " + e.getMessage());
            e.printStackTrace();
        }
    }
    
    private String contactToString(Contact contact) {
        String name = contact.getName().replace("|", "｜");
        String mbti = contact.getMbti().name();
        String notes = contact.getNotes().replace("|", "｜").replace("\n", "\\n");
        String profile = (contact.getAutoGeneratedProfile() != null ? 
            contact.getAutoGeneratedProfile() : "").replace("|", "｜").replace("\n", "\\n"); // 🆕
        String createdAt = contact.getCreatedAt().toString();
        String updatedAt = contact.getUpdatedAt().toString();
        
        return String.format("%s|%s|%s|%s|%s|%s",
            name, mbti, notes, profile, createdAt, updatedAt); // 🆕 profile 추가
    }
    
    private Contact stringToContact(String str) {
        try {
            String[] parts = str.split("\\|");
            if (parts.length < 3) {
                return null;
            }
            
            String name = parts[0].replace("｜", "|");
            MBTI mbti = MBTI.valueOf(parts[1]);
            String notes = parts[2].replace("｜", "|").replace("\\n", "\n");
            
            Contact contact = new Contact(name, mbti, notes);
            
            // 🆕 자동 프로필 로드
            if (parts.length >= 4 && !parts[3].isEmpty()) {
                String profile = parts[3].replace("｜", "|").replace("\\n", "\n");
                contact.setAutoGeneratedProfile(profile);
            }
            
            // 🔧 인덱스 변경 (profile이 추가되어서 +1)
            if (parts.length >= 6) {
                contact.setCreatedAt(LocalDateTime.parse(parts[4]));
                contact.setUpdatedAt(LocalDateTime.parse(parts[5]));
            }
            
            return contact;
            
        } catch (Exception e) {
            System.err.println("⚠️ 연락처 파싱 실패: " + e.getMessage());
            return null;
        }
    }
}
