package model;

import java.time.LocalDateTime;

public class Contact {
    private String name;
    private MBTI mbti;
    private String notes;
    private String autoGeneratedProfile;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
    
    public Contact(String name) {
        this.name = name;
        this.mbti = MBTI.UNKNOWN;
        this.notes = "";
        this.autoGeneratedProfile = null; // 🆕
        this.createdAt = LocalDateTime.now();
        this.updatedAt = LocalDateTime.now();
    }
    
    public Contact(String name, MBTI mbti) {
        this.name = name;
        this.mbti = mbti;
        this.notes = "";
        this.autoGeneratedProfile = null; // 🆕
        this.createdAt = LocalDateTime.now();
        this.updatedAt = LocalDateTime.now();
    }
    
    public Contact(String name, MBTI mbti, String notes) {
        this.name = name;
        this.mbti = mbti;
        this.notes = notes != null ? notes : "";
        this.autoGeneratedProfile = null; // 🆕
        this.createdAt = LocalDateTime.now();
        this.updatedAt = LocalDateTime.now();
    }
    
    public String getName() { return name; }
    public MBTI getMbti() { return mbti; }
    public String getNotes() { return notes; }
    public String getAutoGeneratedProfile() { return autoGeneratedProfile; }
    public LocalDateTime getCreatedAt() { return createdAt; }
    public LocalDateTime getUpdatedAt() { return updatedAt; }
    
    public void setName(String name) {
        this.name = name;
        this.updatedAt = LocalDateTime.now();
    }
    
    public void setMbti(MBTI mbti) {
        this.mbti = mbti;
        this.updatedAt = LocalDateTime.now();
    }
    
    public void setNotes(String notes) {
        this.notes = notes != null ? notes : "";
        this.updatedAt = LocalDateTime.now();
    }

    public void setAutoGeneratedProfile(String profile) {
        this.autoGeneratedProfile = profile;
        this.updatedAt = LocalDateTime.now();
    }
    
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }
    
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
    
    public boolean hasMbti() {
        return mbti != null && mbti != MBTI.UNKNOWN;
    }
    
    public boolean hasAutoProfile() {
        return autoGeneratedProfile != null && !autoGeneratedProfile.trim().isEmpty();
    }

    public String getDisplayInfo() {
        String info = name;
        if (hasMbti()) {
            info += " (" + mbti.getCode() + ")";
        }
        return info;
    }
    
    @Override
    public String toString() {
        return getDisplayInfo();
    }
    
    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (obj == null || getClass() != obj.getClass()) return false;
        Contact contact = (Contact) obj;
        return name.equals(contact.name);
    }
    
    @Override
    public int hashCode() {
        return name.hashCode();
    }
}
